//! [`more1090`] ADS-B receiver application.

use anyhow::{Context, Result};
use clap::{ArgGroup, Parser};
use more1090::{
    ADSBReceiver, CHUNK_LEN,
    cli::try_bit_errors_into_error_correction_level,
    constants::dsp::{CARRIER_FREQUENCY, SAMPLE_RATE_F64},
    mode_s::format_avr,
    receiver::ErrorCorrectionLevel,
    sigmf::{self, SigMFMeta},
};
use num::complex::Complex32;
use std::{
    fs::File,
    io::{BufReader, Read},
    path::{Path, PathBuf},
};

/// ADS-B receiver CLI arguments.
#[derive(Debug, Clone, PartialEq, Parser)]
#[command(version, about, long_about = "more1090 ADS-B receiver",
          group(ArgGroup::new("input").args(["sigmf_file", "stdin"]).required(true)))]
pub struct Args {
    /// SigMF file to decode.
    ///
    /// Decoded messages are written as SigMF annotations in-place to the input
    /// file.
    sigmf_file: Option<PathBuf>,
    /// Read input from stdin.
    ///
    /// Input data must be formatted as native-endian complex float32 at 8
    /// Msps. Decoded messages are printed to stdout in AVR format.
    #[arg(long)]
    stdin: bool,
    /// Include annotations for ADS-B packets that are detected but not
    /// successfully decoded.
    #[arg(long)]
    annotate_detections: bool,
    /// Clear all the SigMF annotations.
    ///
    /// This clears all the annotations of the SigMF file before beginning
    /// decoding. By default only annotations generated by this application (in
    /// a previous run over the same file) are cleared.
    #[arg(long)]
    clear_annotations: bool,
    /// Error correction level.
    ///
    /// This sets the maximum number of bit errors that the ADS-B decoder is
    /// allowed to correct. The maximum correction level allowed is 2 bits.
    #[arg(long, default_value = "2", value_parser = try_bit_errors_into_error_correction_level)]
    error_correction_level: ErrorCorrectionLevel,
    /// Carrier metric threshold.
    ///
    /// This sets the threshold used for carrier detection. The provided default
    /// value is generally a good choice.
    #[arg(long, default_value_t = more1090::constants::dsp::CARRIER_METRIC_THRESHOLD)]
    carrier_metric_threshold: f32,
    /// Preamble metric threshold.
    ///
    /// This sets the threshold used for preamble validation in messages with 2
    /// bit errors. The provided default is generally a good choice.
    #[arg(long, default_value_t = more1090::constants::dsp::PREAMBLE_METRIC_THRESHOLD)]
    preamble_metric_threshold: f32,
}

fn setup_receiver(args: &Args) -> Result<ADSBReceiver> {
    let mut receiver = ADSBReceiver::new();
    receiver.set_error_correction_level(args.error_correction_level);
    receiver.set_carrier_metric_threshold(args.carrier_metric_threshold)?;
    receiver.set_preamble_metric_threshold(args.preamble_metric_threshold)?;
    Ok(receiver)
}

fn decode_sigmf<P: AsRef<Path>>(args: &Args, sigmf_file: P) -> Result<()> {
    let meta_path = sigmf::meta_path(&sigmf_file)?;
    let mut meta = SigMFMeta::from_file(&meta_path)?;
    let datatype = meta.datatype()?.to_string();
    anyhow::ensure!(
        ["ci16_le", "cf32_le"].contains(&datatype.as_str()),
        "SigMF datatype {datatype} unsupported"
    );
    let num_channels = meta.num_channels()?;
    anyhow::ensure!(num_channels == 1, "wrong number of channels (must be 1)");
    let sample_rate = meta.sample_rate()?;
    anyhow::ensure!(
        sample_rate == SAMPLE_RATE_F64,
        "wrong sample rate {sample_rate} (must be {SAMPLE_RATE_F64})"
    );
    let frequency = meta.frequency()?;
    anyhow::ensure!(
        frequency == CARRIER_FREQUENCY,
        "wrong RF frequency {frequency} (must be {CARRIER_FREQUENCY})",
    );
    if args.clear_annotations {
        meta.clear_annotations()
    } else {
        meta.clear_annotations_generator(sigmf::GENERATOR);
    }

    let mut receiver = setup_receiver(args)?;

    let sigmf_data =
        File::open(sigmf::data_path(&sigmf_file)?).context("failed to open sigmf-data file")?;
    let sigmf_data_len = sigmf_data.metadata()?.len();
    let mut num_detections = 0;
    let mut num_decodes = 0;

    macro_rules! main_loop {
        ($reader:ident) => {{
            let mut sigmf_data = sigmf::$reader::new(BufReader::new(sigmf_data), sigmf_data_len)?;
            while let Some(chunk) = sigmf_data.read() {
                let chunk = chunk?;
                if let Some(packet) = receiver.process_chunk(chunk) {
                    if args.annotate_detections || packet.decode.is_some() {
                        meta.add_adsb_packet_annotation(
                            packet,
                            &if packet.decode.is_some() {
                                format!("ADS-B packet {num_decodes}")
                            } else {
                                format!("ADS-B detection {num_detections}")
                            },
                        );
                    }
                    if packet.decode.is_some() {
                        num_decodes += 1;
                    }
                    num_detections += 1;
                }
            }
        }};
    }

    match datatype.as_str() {
        "ci16_le" => main_loop!(CI16LEReader),
        "cf32_le" => main_loop!(CF32LEReader),
        _ => unreachable!(),
    }

    meta.to_file(meta_path)?;

    Ok(())
}

// Compile time assertion checking that Complex32 uses 8 bytes (the same as 2x
// f32). This serves to support the unsafe slice transmutation that is done in
// decode_stdin.
const _: () = {
    assert!(
        std::mem::size_of::<Complex32>() == 8,
        "Complex32 does not have 8 bytes of size"
    );
};

fn decode_stdin(args: &Args) -> Result<()> {
    let mut receiver = setup_receiver(args)?;
    let stdin = std::io::stdin();
    let mut handle = stdin.lock();
    const BUFSIZE: usize = 80_000; // 10 milliseconds
    let mut buffer: more1090::A<[Complex32; BUFSIZE]> = aligned::Aligned([Complex32::default(); _]);
    loop {
        {
            // SAFETY: it is safe to view the buffer as a slice of u8's and to read
            // data from stdin into the buffer because any bit pattern is a valid
            // Complex32 value, and an array of Complex32's has no padding.
            let s = unsafe {
                std::slice::from_raw_parts_mut(
                    buffer.as_mut_ptr().cast::<u8>(),
                    BUFSIZE * std::mem::size_of::<Complex32>(),
                )
            };
            if let Err(err) = handle.read_exact(s) {
                if err.kind() == std::io::ErrorKind::UnexpectedEof {
                    // Note that this drops up to 10 milliseconds of input when
                    // reaching EOF. This is acceptable, because the main use
                    // case for reading from stdin is real time decoding of an
                    // endless stream of IQ data.
                    return Ok(());
                } else {
                    Err(err)?;
                }
            }
        }
        for chunk in buffer.as_chunks::<CHUNK_LEN>().0.iter() {
            if let Some(packet) = receiver.process_chunk(chunk)
                && let Some(decode) = &packet.decode
            {
                println!("{}", format_avr(&decode.message));
            }
        }
    }
}

pub fn main() -> Result<()> {
    let args = Args::parse();

    if let Some(sigmf_file) = &args.sigmf_file {
        decode_sigmf(&args, sigmf_file)?;
    } else {
        decode_stdin(&args)?;
    }
    Ok(())
}
